#!/bin/bash

_add_column(){
    REPORT_SOURCE="${1}"
    SECTION="${2}"
    KEY="${3}"
    VALUE="${4}"
    if [[ "${FILE_NUMBER}" = "0" ]] ; then
        if [[ "${REPORT_SOURCE}" = "ffprobe" ]] ; then
            CSV_HEADER+="${SECTION}.${KEY},"
        elif [[ "${REPORT_SOURCE}" = "astats" ]] ; then
            CSV_HEADER+="${KEY// /_}_${SECTION},"
        elif [[ "${REPORT_SOURCE}" = "local" ]] ; then
            CSV_HEADER+="${KEY},"
        fi
    fi
    if [[ "${REPORT_SOURCE}" = "ffprobe" ]] ; then
        CSV_ROW+="$(_flat_ffprobe_parse "${FFPROBE_REPORT}" "${SECTION}.${KEY}"),"
    elif [[ "${REPORT_SOURCE}" = "astats" ]] ; then
        CSV_ROW+="$(_astats_parse "${FILTER_REPORT}" "${SECTION}" "${KEY}"),"
    elif [[ "${REPORT_SOURCE}" = "local" ]] ; then
        CSV_ROW+="${VALUE},"
    else
        _report -w "Unexpected error in _add_column, REPORT_SOURCE=(${REPORT_SOURCE}), SECTION=(${SECTION}), KEY=(${KEY})"
    fi
}

_check_dependencies(){
    while [ "${*}" != "" ] ; do
        DEPENDENCY="${1}"
        if [ ! $(which "${DEPENDENCY}") ] ; then
            _report -wt "This script requires ${DEPENDENCY} to run but it is not installed"
            DEPS_OK=NO
        fi
        shift
    done
    if [[ "${DEPS_OK}" = "NO" ]]; then
        _report -wt "Unmet dependencies"
        _report -wt "Aborting!"
        exit 1
    else
        return 0
    fi
}

_find_a_font(){
    if [[ -f "/Library/Fonts/Andale Mono.ttf" ]] ; then
        FONT_FILE="/Library/Fonts/Andale Mono.ttf"
    elif [[ -f "/System/Library/Fonts/Supplemental/Andale Mono.ttf" ]] ; then
        FONT_FILE="/System/Library/Fonts/Supplemental/Andale Mono.ttf"
    elif [[ -f "/System/Library/Fonts/Monaco.dfont" ]] ; then
        FONT_FILE="/System/Library/Fonts/Monaco.dfont"
    elif [[ -f "/Library/Fonts/Microsoft/Lucida Console.ttf" ]] ; then
        FONT_FILE="/Library/Fonts/Microsoft/Lucida\Console.ttf"
    elif [[ -f "/Library/Fonts/LetterGothicStd.otf" ]] ; then
        FONT_FILE="/Library/Fonts/LetterGothicStd.otf"
    else
        _report -wt "astatsaudit can't find a preferred font to use."
    fi
}

_finish_xml(){
    INVENTORY_XML="${1}"
    xml select \
        -N "rdf=http://www.w3.org/1999/02/22-rdf-syntax-ns#" \
        -N "asa=https://github.com/amiaopensource/astatsaudit" \
        -N "ffprobe=http://www.ffmpeg.org/schema/ffprobe" \
        -N "astats=https://ffmpeg.org/ffmpeg-filters.html#astats" \
        -N "bwfme=https://mediaarea.net/BWFMetaEdit" \
        -t \
            --elem "rdf:RDF" \
            --match "//f" \
            --elem "rdf:Description" \
                --attr "rdf:about" -v "." -b \
            --elem "asa:stats" \
                --elem "asa:dateTime" -v "date:date-time()" -b \
            -b \
            --elem "ffprobe:report" \
                  --attr "settings" -o "$(echo ${FFPROBE_CMD[@]})" -b \
                  --copy-of "document(@ff)/*" -b \
            --elem "astats:report" --copy-of "document(@astats)/astats/text()" -b \
            --elem "bwfme:fullReport" \
                  --copy-of "document(@bwf)/*" \
        "${INVENTORY_XML}" | xml fo
}

_flat_ffprobe_parse(){
    FFPROBE_DOC="${1}"
    KEY="${2}"
    VALUE="$(grep "^${KEY}=" "${FFPROBE_DOC}" | cut -d "=" -f2- | sed -e 's/^"//' -e 's/"$//')"
    VALUE_LINE_COUNT="$(echo -n "${VALUE}" | grep -c '^')"
    if [[ "${VALUE_LINE_COUNT}" > 1 ]] ; then
        _report -w "The parsed value for '${KEY}' is in ${VALUE_LINE_COUNT} lines, which may be unintended"
    fi
    echo -n "${VALUE}"
}

_astats_parse(){
    ASTATS_DOC="${1}"
    SECTION="${2}"
    KEY="${3}"
    if [[ "${SECTION}" == "Overall" ]] ; then
        VALUE="$(sed '1,/Overall$/d' "${ASTATS_DOC}" | grep "] ${KEY}:" | cut -d : -f2- | sed 's/ //g')"
    else
        VALUE="$(sed -n "s/Overall$/Channel: X/g;/Channel: ${SECTION}/,/Channel/p" "${ASTATS_DOC}" | grep "] ${KEY}:" | cut -d : -f2- | sed 's/ //g')"
    fi
    VALUE_LINE_COUNT="$(echo -n "${VALUE}" | grep -c '^')"
    if [[ "${VALUE_LINE_COUNT}" > 1 ]] ; then
        _report -w "The parsed value for '${KEY}' is in ${VALUE_LINE_COUNT} lines, which may be unintended"
    fi
    echo -n "${VALUE}"
}

_get_iso8601(){
    date +%FT%T
}

_get_iso8601_c(){
    date +%Y%m%d-%H%M%S
}

_maketemp(){
    mktemp -q -t "$(basename "${0}").XXXXXX"
    if [ "${?}" -ne 0 ]; then
        echo "${0}: Can't create temp file, exiting..."
        exit 1
    fi
}

_report(){
    local RED="$(tput setaf 1)"    # Red      - For Warnings
    local GREEN="$(tput setaf 2)"  # Green    - For Declarations
    local BLUE="$(tput setaf 4)"   # Blue     - For Questions
    local MAGENTA="$(tput setaf 5)" # Magenta - For Verbose Statements
    local NC="$(tput sgr0)"        # No Color
    local COLOR=""
    local STARTMESSAGE=""
    local ECHOOPT=""
    local VERBOSE_CHECK=false
    OPTIND=1
    while getopts "vqdwstn" opt ; do
        case "${opt}" in
            v) VERBOSE_CHECK=true ;
               COLOR="${MAGENTA}" ;
               STARTMESSAGE+="#" ;; # only output the message if DV_VERBOSE=true
            q) COLOR="${BLUE}" ;;                        # question mode, use color blue
            d) COLOR="${GREEN}" ;;                       # declaration mode, use color green
            w) COLOR="${RED}" ;;                         # warning mode, use color red
            s) STARTMESSAGE+=([${SCRIPTNAME}] ) ;;       # prepend scriptname to the message
            t) STARTMESSAGE+=($(_get_iso8601) '- ' ) ;;  # prepend timestamp to the message
            n) ECHOOPT="-n" ;;                           # to avoid line breaks after echo
        esac
    done
    shift "$((OPTIND-1))"
    MESSAGE="${1}"
    if ! "${VERBOSE_CHECK}" ; then
        >&2 echo ${ECHOOPT} "${COLOR}${STARTMESSAGE[@]}${MESSAGE}${NC}"
    fi
}

_ss_to_hhmmss(){
    # if milliseconds are used it will round down to nearest second for instance 60.9, will return 1:00
    INT="${1%.*}"
    [[ -z "$INT" ]] && INT="0"
    DEC="$(echo "${1#*.}" | head -c 3)"
    printf "%02d\:%02d\:%02d.${DEC}\n" $(($INT/3600)) $(($INT%3600/60)) $(($INT%60))
}

_get_metadata(){
    FILENAME="${1}"
    BASENAME=$(basename "${FILENAME}")
    FILTER_REPORT="$(_maketemp)"
    FILTER_REPORT_XMLD="${2}"
    FFPROBE_REPORT="$(_maketemp)"
    ffmpeg -nostdin -i "${FILENAME}" -vn -filter_complex "astats" -f null - 2>&1 |  tr "\r" "\n" > "${FILTER_REPORT}"
    {
        echo "<astats>"
        grep "Parsed_astats" "${FILTER_REPORT}" | cut -d "]" -f2- | sed 's/^ //g'
        echo "</astats>"
    } > "${FILTER_REPORT_XMLD}"
    ffprobe -i "${FILENAME}" -show_format -show_streams -of flat > "${FFPROBE_REPORT}"
    BWFMETAEDIT_REPORT=$(bwfmetaedit "$FILENAME" 2>&1 | awk '{printf "%s+",$0} END {print ""}')
}

_get_csv_row(){
    # this function expects to process the following variables:
    # FILTER_REPORT, FFPROBE_REPORT, BWFMETAEDIT_REPORT
    unset CSV_ROW

    # the following _add_column functions use the following arguments
    # 1: 'astats to read from FILTER_REPORT
    #    'ffprobe' to read from FFPROBE_REPORT
    #    'local' to print local key/value pairs
    # 2: if $1=astats the $2 is the channel number or 'Overall'
    #    if $2=ffprobe then $2 is the section: format or streams
    #    if $1=local then $2 is unused
    # 3: the value or variable to parse from the referenced report
    # 4: if $1=local then this is the value for the $3 variable
    _add_column astats  1       "Bit depth"
    _add_column astats  2       "Bit depth"
    _add_column astats  Overall "Bit depth"
    _add_column ffprobe streams stream.0.channels
    _add_column ffprobe streams stream.0.codec_name
    _add_column astats  1       "Crest factor"
    _add_column astats  2       "Crest factor"
    _add_column astats  1       "DC offset"
    _add_column astats  2       "DC offset"
    _add_column astats  Overall "DC offset"
    _add_column ffprobe format  duration
    _add_column astats  1       "Dynamic range"
    _add_column astats  2       "Dynamic range"
    _add_column local   ""      filename "${BASENAME}"
    _add_column astats  1       "Flat factor"
    _add_column astats  2       "Flat factor"
    _add_column astats  Overall "Flat factor"
    _add_column astats  1       "Max difference"
    _add_column astats  2       "Max difference"
    _add_column astats  Overall "Max difference"
    _add_column astats  1       "Max level"
    _add_column astats  2       "Max level"
    _add_column astats  Overall "Max level"
    _add_column astats  1       "Mean difference"
    _add_column astats  2       "Mean difference"
    _add_column astats  Overall "Mean difference"
    _add_column astats  1       "Min difference"
    _add_column astats  2       "Min difference"
    _add_column astats  Overall "Min difference"
    _add_column astats  1       "Min level"
    _add_column astats  2       "Min level"
    _add_column astats  Overall "Min level"
    _add_column astats  1       "Noise floor dB"
    _add_column astats  2       "Noise floor dB"
    _add_column astats  Overall "Noise floor dB"
    _add_column astats  1       "Noise floor count"
    _add_column astats  2       "Noise floor count"
    _add_column astats  Overall "Noise floor count"
    _add_column astats  Overall "Number of samples"
    _add_column astats  1       "Peak count"
    _add_column astats  2       "Peak count"
    _add_column astats  Overall "Peak count"
    _add_column astats  1       "Peak level dB"
    _add_column astats  2       "Peak level dB"
    _add_column astats  Overall "Peak level dB"
    _add_column astats  1       "RMS difference"
    _add_column astats  2       "RMS difference"
    _add_column astats  Overall "RMS difference"
    _add_column astats  1       "RMS level dB"
    _add_column astats  2       "RMS level dB"
    _add_column astats  Overall "RMS level dB"
    _add_column astats  1       "RMS peak dB"
    _add_column astats  2       "RMS peak dB"
    _add_column astats  Overall "RMS peak dB"
    _add_column astats  1       "RMS trough dB"
    _add_column astats  2       "RMS trough dB"
    _add_column astats  Overall "RMS trough dB"
    _add_column ffprobe streams stream.0.sample_rate
    _add_column astats  1       "Zero crossings"
    _add_column astats  2       "Zero crossings"
    _add_column astats  1       "Zero crossings rate"
    _add_column astats  2       "Zero crossings rate"
    _add_column local   ""      bwfmetaedit "${BWFMETAEDIT_REPORT}"
}

_make_graph(){
    FILENAME="${1}"
    BASENAME=$(basename "${FILENAME}")
    # image settings
    AUDIO_SAMPLE_RATE=48000
    HEADER_HEIGHT=24
    HEADER_HEIGHT_BIG=$(echo "${HEADER_HEIGHT} * 2" | bc)
    TIMELINE_FONTSIZE=16
    DRAWGRAPH_SETTINGS="bg=Black"
    BORDER_COLOR="LightGrey"
    HORIZONTAL_MARKINGS_240="drawgrid=thickness=1:color=${BORDER_COLOR}@0.2:height=ih/16,drawgrid=thickness=1:color=${BORDER_COLOR}@0.5:height=ih/4,drawgrid=thickness=1:color=${BORDER_COLOR}@0.8:height=ih/2"
    HORIZONTAL_MARKINGS_120="drawgrid=thickness=1:color=${BORDER_COLOR}@0.2:height=ih/8,drawgrid=thickness=1:color=${BORDER_COLOR}@0.5:height=ih/4,drawgrid=thickness=1:color=${BORDER_COLOR}@0.8:height=ih/2"
    GRAPH_W=6000
    AUDIO_FRAME_SIZE="$(echo "((${DURATION}*${AUDIO_SAMPLE_RATE})/${GRAPH_W})+1" | bc)"
    # adding 0.5 in the above equation to ensure that the result is rounded to the nearest integer, rather than simply rounded down
    AUDIOFORMAT="aresample=${AUDIO_SAMPLE_RATE},aformat=sample_fmts=dbl,asetnsamples=n=${AUDIO_FRAME_SIZE}:p=0"
    VERTICAL_MARKINGS=$(echo "${GRAPH_W} / 150" | bc)
    GRAPH_H="384"
    PAD_W="240"

    unset TIMELINE
    COUNTER=0
    while [ "${COUNTER}" -lt "${VERTICAL_MARKINGS}" ]; do
        ((COUNTER++))
        MARK="$(echo "scale=6; $DURATION * ($COUNTER / $VERTICAL_MARKINGS)" | bc)"
        MARK_X="$(echo "scale=6; $GRAPH_W * ($COUNTER / $VERTICAL_MARKINGS)" | bc)"
        MARK_TIME="$(_ss_to_hhmmss "${MARK}")"
        TIMELINE+=",drawtext=fontfile=${FONT_FILE}:fontcolor=black:fontsize=${TIMELINE_FONTSIZE}:text='${MARK_TIME}':x=${MARK_X}-text_w:y=(${HEADER_HEIGHT}-${TIMELINE_FONTSIZE})/2"
    done
    GRAPH_FILTER="asplit=2[j][k];
        `#timeline`
        color=c=${BORDER_COLOR}:s=${GRAPH_W}x${HEADER_HEIGHT}${TIMELINE},split=4[top1][top2][top3][top4];
        color=c=${BORDER_COLOR}:s=${GRAPH_W}x${HEADER_HEIGHT_BIG},drawtext=fontfile=${FONT_FILE}:fontcolor=black:fontsize=36:text='Audio QC Graph\:   Filename\: ${BASENAME},   Duration\: $(_ss_to_hhmmss "${DURATION}"),   Audio Frame Size\: ${AUDIO_FRAME_SIZE}'[Header];
        `#peak/rms left`color=c=${BORDER_COLOR}:s=${GRAPH_W}x${HEADER_HEIGHT},drawtext=fontfile=${FONT_FILE}:fontcolor=black:fontsize=24:text='Peak Level / RMS Level Left -70...0dB. Yellow=peak level, purple=RMS level'[peakLH];
        `#peak/rms right`color=c=${BORDER_COLOR}:s=${GRAPH_W}x${HEADER_HEIGHT},drawtext=fontfile=${FONT_FILE}:fontcolor=black:fontsize=24:text='Peak Level / RMS Level Right -70...0dB. Yellow=peak level, purple=RMS level'[peakRH];
        `#min/max`color=c=${BORDER_COLOR}:s=${GRAPH_W}x${HEADER_HEIGHT},drawtext=fontfile=${FONT_FILE}:fontcolor=black:fontsize=24:text='Min/Max Level -1...1. Blue=channel 1, pink=channel 2.'[minmaxH];
        `#phase`color=c=${BORDER_COLOR}:s=${GRAPH_W}x${HEADER_HEIGHT},drawtext=fontfile=${FONT_FILE}:fontcolor=black:fontsize=24:text='Phase -1 (out of phase)...1 (in phase). Green=+0.9 to +1, reasonable for mono/error for stereo. Yellow=0 to +0.9, error for mono/reasonable for stereo. Orange=0 to -0.5, error for mono/strong possibility of error for stereo if occurring more than briefly. Red=-0.5 to -1, error for mono/strong possibility of error for stereo.'[phaseH];
        `#dc offset`color=c=${BORDER_COLOR}:s=${GRAPH_W}x${HEADER_HEIGHT},drawtext=fontfile=${FONT_FILE}:fontcolor=black:fontsize=24:text='DC Offset -0.01...0.01. Offsetting of the mean amplitude displacement from zero, in dB. Shows cumulative average over recording; the offset should equal 0 by the end of the graph.'[dcoffH];
        `#crest`color=c=${BORDER_COLOR}:s=${GRAPH_W}x${HEADER_HEIGHT},drawtext=fontfile=${FONT_FILE}:fontcolor=black:fontsize=24:text='Crest Factor 0...10. Ratio of peak to RMS level (not in dB). Blue=channel 1, pink=channel 2.`#High levels may indicate prior compression`'[crestH];
        [j]${AUDIOFORMAT},astats=metadata=1:reset=1,asplit=5[astats1][astats2][astats3][astats4][astats5];
            [astats1]adrawgraph=${DRAWGRAPH_SETTINGS}:
                m1=lavfi.astats.1.Peak_level:fg1=0xFFFF0000:
                m2=lavfi.astats.1.RMS_level:fg2=0xFF00FFFF:
                max=0:min=-70:
                slide=picture:
                mode=line:
                s=${GRAPH_W}x${GRAPH_H},${HORIZONTAL_MARKINGS_240}[peakL1];
            [astats2]adrawgraph=${DRAWGRAPH_SETTINGS}:
                m1=lavfi.astats.2.Peak_level:fg1=0xFFFF00FF:
                m2=lavfi.astats.2.RMS_level:fg2=0xFF00FFFF:
                max=0:min=-70:
                slide=picture:
                mode=line:
                s=${GRAPH_W}x${GRAPH_H},${HORIZONTAL_MARKINGS_240}[peakR1];
            [astats3]adrawgraph=${DRAWGRAPH_SETTINGS}:
                m1=lavfi.astats.1.Max_level:fg1=0xFFFF00FF:
                m2=lavfi.astats.2.Max_level:fg2=0xFFFF0000:
                m3=lavfi.astats.1.Min_level:fg3=0xFFFF00FF:
                m4=lavfi.astats.2.Min_level:fg4=0xFFFF0000:
                min=-1:max=1:
                slide=picture:
                s=${GRAPH_W}x${GRAPH_H},${HORIZONTAL_MARKINGS_240}[minmax1];
            [astats4]adrawgraph=${DRAWGRAPH_SETTINGS}:
                m1=lavfi.astats.1.DC_offset:fg1=if(gte(VAL\,0.005)\,0xFF0000FF\,if(lte(VAL\,-0.005)\,0xFF0000FF\,0xFF00FF00)):
                m2=lavfi.astats.2.DC_offset:
                min=-0.01:max=0.01:
                slide=picture:
                s=${GRAPH_W}x${GRAPH_H},${HORIZONTAL_MARKINGS_240}[dcoff1];
            [astats5]adrawgraph=${DRAWGRAPH_SETTINGS}:
                m1=lavfi.astats.1.Crest_factor:fg1=0xFFFF00FF:
                m2=lavfi.astats.2.Crest_factor:fg2=0xFFFF0000:
                max=10:min=0:
                slide=picture:
                mode=line:
                s=${GRAPH_W}x${GRAPH_H},${HORIZONTAL_MARKINGS_240}[crest1];
        [k]${AUDIOFORMAT},aphasemeter=video=0,
            adrawgraph=${DRAWGRAPH_SETTINGS}:
                m1=lavfi.aphasemeter.phase:fg1=if(gte(VAL\,0.9)\,0xFF00FF00\,if(gte(VAL\,0)\,0xFF00FFFF\,if(gte(VAL\,-0.5)\,0xFF0096FF\,0xFF0000FF))):
                max=1:min=-1:
                slide=picture:
                s=${GRAPH_W}x${GRAPH_H},${HORIZONTAL_MARKINGS_240}[phase1];
        [Header]
        [top1][peakLH][peakL1][peakRH][peakR1]
        [top2][minmaxH][minmax1][phaseH][phase1]
        [top3][dcoffH][dcoff1][crestH][crest1]
        [top4]vstack=17,drawgrid=thickness=1:color=gray@0.5:width=iw/${VERTICAL_MARKINGS},drawgrid=thickness=1:color=${BORDER_COLOR}@0.2:width=(iw/${VERTICAL_MARKINGS})/10[graph];
        color=c=${BORDER_COLOR}:s=${PAD_W}x${HEADER_HEIGHT_BIG}[HeaderG];
        color=c=${BORDER_COLOR}:s=${PAD_W}x${HEADER_HEIGHT},split=10[top1G][top2G][top3G][top4G][peakLHG][peakRHG][minmaxHG][phaseHG][dcoffHG][crestHG];
        `#1-1_240p_grat`color=c=${BORDER_COLOR}:s=${PAD_W}x${GRAPH_H},drawtext=fontfile=${FONT_FILE}:fontcolor=black:fontsize=${TIMELINE_FONTSIZE}:y=h*0.52:x=w*0.7:text='0',drawtext=fontfile=${FONT_FILE}:fontcolor=black:fontsize=${TIMELINE_FONTSIZE}:y=h*0.77:x=w*0.7:text='-0.5',drawtext=fontfile=${FONT_FILE}:fontcolor=black:fontsize=${TIMELINE_FONTSIZE}:y=h*0.27:x=w*0.7:text='+0.5',drawgrid=thickness=1:color=black@0.2:height=ih/16,drawgrid=thickness=1:color=black@0.5:height=ih/4,drawgrid=thickness=1:color=black@0.8:height=ih/2,split=4[minmax1G][phase1G][crest1G][dcoff1G];
        `#0-70_240p_grat`color=c=${BORDER_COLOR}:s=${PAD_W}x${GRAPH_H},drawtext=fontfile=${FONT_FILE}:fontcolor=black:fontsize=${TIMELINE_FONTSIZE}:y=h*0.52:x=w*0.7:text='-35',drawtext=fontfile=${FONT_FILE}:fontcolor=black:fontsize=${TIMELINE_FONTSIZE}:y=h*0.77:x=w*0.7:text='-52.5',drawtext=fontfile=${FONT_FILE}:fontcolor=black:fontsize=${TIMELINE_FONTSIZE}:y=h*0.27:x=w*0.7:text='-17.5',drawtext=fontfile=${FONT_FILE}:fontcolor=black:fontsize=${TIMELINE_FONTSIZE}:y=h*0.02:x=w*0.7:text='0',drawgrid=thickness=1:color=black@0.2:height=ih/16,drawgrid=thickness=1:color=black@0.5:height=ih/4,drawgrid=thickness=1:color=black@0.8:height=ih/2,split=2[peakL1G][peakR1G];
        [HeaderG]
        [top1G][peakLHG][peakL1G][peakRHG][peakR1G]
        [top2G][minmaxHG][minmax1G][phaseHG][phase1G]
        [top3G][dcoffHG][dcoff1G][crestHG][crest1G]
        [top4G]vstack=17[grat];
        [grat][graph]hstack=2[chart]"
    ffmpeg -nostdin -y -i "$FILENAME" -filter_complex "${GRAPH_FILTER}" \
        -map "[chart]" -vframes 1 ./"${BASENAME}_audio_report2.png"
}

_process_file(){
    FILENAME="$1"
    unset CSV_ROW
    FILTER_TMP_XMLD="$(_maketemp)"
    IS_AUDIO="$(ffprobe "${FFMPEG_VERBOSE[@]}" -v 0 "${FILENAME}" -show_entries stream=codec_type -select_streams a:0 -of default=nk=1:nw=1)"
    if [[ "${IS_AUDIO}" = "audio" ]] ; then
        _get_metadata "${FILENAME}" "${FILTER_TMP_XMLD}"
        _get_csv_row "${FILENAME}"
        # gather xml data
        FFMPEG_TMP="${FILES_XML_TMP}.ff.${FILE_NUMBER}.xml"
        BWFME_TMP="${FILES_XML_TMP}.bwf.${FILE_NUMBER}.xml"
        echo "<f ff=\"${FFMPEG_TMP}\" bwf=\"${BWFME_TMP}\" astats=\"${FILTER_TMP_XMLD}\">$(echo "${FILENAME}" | sed 's/.*\/\|.*\///g')</f>" >> "${FILES_XML_TMP}"
        FFPROBE_CMD=(ffprobe -v 0 "${FILENAME}" "${FFPROBE_SETTINGS[@]}")
        "${FFPROBE_CMD[@]}" > "${FFMPEG_TMP}"
        BWFME_CMD=(bwfmetaedit --out-core-xml="${BWFME_TMP}" "${FILENAME}")
        "${BWFME_CMD[@]}"
        # express csv row (with header if on first row)
        if [[ "${FILE_NUMBER}" = "0" ]] ; then
            echo "${CSV_HEADER}" | sed 's/.$//' > "${OUTPUT_CSV}"
        fi
        echo "${CSV_ROW}" | sed 's/.$//' >> "${OUTPUT_CSV}"
        # variables to keep
        DURATION=$(_flat_ffprobe_parse "${FFPROBE_REPORT}" format.duration)
        _make_graph "${FILENAME}"
    else
        _report -d "Skipping ${FILENAME}. (no audio stream found)"
    fi
}

_check_dependencies bwfmetaedit ffmpeg ffprobe
_find_a_font

FILE_NUMBER="0"
CSV_HEADER=""
CSV_ROW=""

INPUT="$1"
FFPROBE_SETTINGS=(-of xml=x=1:q=1 -noprivate -show_format -show_streams)
NOW="$(_get_iso8601_c)"
if [[ -f "${INPUT}" ]] ; then
    OUTPUT_CSV="astatsaudit_${NOW}.csv"
    while [[ "${@}" != "" ]] ; do
        INPUT="$1"
        FILES_XML_TMP="$(_maketemp)"
        OUTPUT_XML="${INPUT}.astatsaudit.xml"
        _process_file "${INPUT}"
        _finish_xml "${FILES_XML_TMP}" > "${OUTPUT_XML}"
        ((FILE_NUMBER++))
        shift
    done
elif [[ -d "${INPUT}" ]] ; then
    FILES_XML_TMP="$(_maketemp)"
    OUTPUT_XML="${INPUT}/astatsaudit.xml"
    OUTPUT_CSV="${INPUT}/astatsaudit.csv"
    echo "<files>" > "${FILES_XML_TMP}"
    while read FILE ; do
        _process_file "${FILE}"
        ((FILE_NUMBER++))
    done < <(find "${INPUT}" -maxdepth 1 -type f ! -name ".*")
    echo "</files>" >> "${FILES_XML_TMP}"
    _finish_xml "${FILES_XML_TMP}" > "${OUTPUT_XML}"
fi
